### ISSUE TITLE
ES6 TypeError: target.addListener is not a function

### ISSUE THREAD

**Issue by donl** [appy-one/acebase#177]
When using node.js import syntax I am getting the following error:

```
file:///app/node_modules/acebase/dist/esm/ipc/index.js:23
            target.addListener(event, handler);
                   ^

TypeError: target.addListener is not a function
    at bindEventHandler (file:///app/node_modules/acebase/dist/esm/ipc/index.js:23:20)
    at new IPCPeer (file:///app/node_modules/acebase/dist/esm/ipc/index.js:31:13)
    at new Storage (file:///app/node_modules/acebase/dist/esm/storage/index.js:409:24)
    at new AceBaseStorage (file:///app/node_modules/acebase/dist/esm/storage/binary/index.js:93:

    at new LocalApi (file:///app/node_modules/acebase/dist/esm/api-local.js:28:32)
    at new AceBase (file:///app/node_modules/acebase/dist/esm/acebase-local.js:33:20)
    at new AceBaseServer (file:///app/node_modules/acebase-server/dist/esm/server.js:53:19)
    at file:///app/server.js:131:16
```

**Comment by appy-one** [comment]
I have disabled usage of the generated ESM modules for now, updating your `acebase-server` will also update your `acebase` package and fix this issue.
