### ISSUE TITLE
Error: Unexpected token in storage-acebase.js

### ISSUE THREAD

**Issue by holeq** [appy-one/acebase#55]
Hello. I faced the problem in version 1.12.3.
Node v13.10.1 on Windows 10

...\node_modules\acebase\src\storage-acebase.js:979
            if (this.settings.transactions?.log !== true) { throw new Error('Transaction logging is not enabled'); }
                                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\PROJECTS\njs-querize\node_modules\acebase\src\api-local.js:3:52)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)

**Comment by appy-one** [comment]
The optional chaining operator `?.` is supported by Node.js 14+. If you can update, do that. I will change the code to be backward compatible with older Node.js versions again but updating is your quickest solution for now

**Comment by holeq** [comment]
I hear you. Thank you.

**Comment by appy-one** [comment]
I published the fix for this in acebase v1.12.4
